# AWS DevOps Pipeline YAML for MLOps Project

# Define stages of the pipeline
stages:
  - name: Build
    actions:
      - name: Build_Image
        action_type: 'Build'
        input_artifacts: []
        output_artifacts:
          - name: 'mlops_project_image'
        configuration:
          ProjectName: 'MLOpsProject'
          EnvironmentVariables:
            - Name: 'AWS_DEFAULT_REGION'
              Value: 'your_aws_region'
            - Name: 'DOCKER_REGISTRY'
              Value: 'your_ecr_repository_uri'
            - Name: 'IMAGE_TAG'
              Value: 'latest'
            # Add other environment variables as needed
          RunOrder: 1

  - name: Deploy
    actions:
      - name: Deploy_to_Kubernetes
        action_type: 'Deploy'
        input_artifacts:
          - name: 'mlops_project_image'
        configuration:
          ClusterName: 'your_eks_cluster_name'
          ServiceRole: 'your_iam_service_role'
          Region: 'your_aws_region'
          InputArtifacts:
            - Name: 'mlops_project_image'
          RunOrder: 1

# Define artifacts to be generated by the pipeline
artifacts:
  - name: mlops_project_image
    type: 'Amazon S3'

# Define service role and permissions
serviceRole: 'arn:aws:iam::your_account_id:role/service-role/AWSCodePipelineServiceRole'

# Define AWS CodePipeline structure
pipeline:
  name: MLOpsPipeline
  roleArn: 'arn:aws:iam::your_account_id:role/service-role/AWSCodePipelineServiceRole'
  artifactStore:
    location: 'your-s3-bucket'
    type: 'S3'
